### ISSUE TITLE
Dicas de boas práticas

### ISSUE THREAD

**Issue by jlcvp** [hericlessilva/C-progresso#1]
Fala cara, Só deixando umas dicas aqui pra melhorar o código:

1. Sempre coloca a extensão no arquivo (.c / .cpp) pra o github entender o tipo e fazer o destaque de sintaxe e ficar mais legível pra quem for olhar teu código, por exemplo, no teu estudo 1 de vetores:

### Sem extensão .c
```
#include <stdio.h>

int main()
{
    int num;
    int vet[10]={2,4,6,8,10,12,14,16,18,20};
    printf("Digite um numero de 0 a 9:");
    scanf("%d", &num);
    printf("O elemento encontrado no vetor foi %d", vet[num]);
    return 0;
}
```

### COM extensão .c
```c
#include <stdio.h>

int main()
{
    int num;
    int vet[10]={2,4,6,8,10,12,14,16,18,20};
    printf("Digite um numero de 0 a 9:");
    scanf("%d", &num);
    printf("O elemento encontrado no vetor foi %d", vet[num]);
    return 0;
}
```

2. Outra dica seria sempre usar a identação adequada. Geralmente as IDE's tem formatadores automáticos que já corrigem qualquer problema na identação. Por exemplo, no teu estudo 2 de vetores.

### Sem identação
```
#include <stdio.h>

int main(){
int vet[10],posicao;
for (posicao=0;posicao<10;posicao++)
{
scanf ("%d",&vet[posicao]);
}
for (posicao=9;posicao>=0;posicao--)
{
printf ("%d \n",vet[posicao]);
}
return 0;
}
```

### Com identação
```c
#include <stdio.h>

int main() {
  int vet[10], posicao;
  for (posicao = 0; posicao < 10; posicao++) {
    scanf("%d", & vet[posicao]);
  }
  for (posicao = 9; posicao >= 0; posicao--) {
    printf("%d \n", vet[posicao]);
  }
  return 0;
}
```

**Comment by hericlessilva** [comment]
Amigo obrigado pela sua atenção, acabei de aplicar as boa práticas como recomendou. Abraços!
